USE budgeter;

CREATE TABLE Category
(
    ID INT IDENTITY(1,1) CONSTRAINT PK_Category_ID PRIMARY KEY,
    [Name] VARCHAR(100) NOT NULL,
    BankAccountID INT NOT NULL FOREIGN KEY REFERENCES BankAccount(ID),
    IsCredit BIT NOT NULL
);