USE budgeter;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Job')
BEGIN
    CREATE TABLE dbo.Job
    (
        ID INT PRIMARY KEY CLUSTERED,
        [Name] VARCHAR(50)
    );
END;