USE budgeter;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Job')
BEGIN
    CREATE TABLE dbo.Job
    (
        ID INT PRIMARY KEY CLUSTERED,
        [Name] VARCHAR(50)
    );
END;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Job' AND COLUMN_NAME = 'AnotherColumn')
BEGIN
    ALTER TABLE Job ADD AnotherColumn BIT NOT NULL DEFAULT(0);
END;