USE budgeter;

CREATE TABLE MonthlyBalance
(
	ID INT IDENTITY(1,1) CONSTRAINT PK_MonthlyBalance_ID PRIMARY KEY,
	MonthID INT NOT NULL FOREIGN KEY REFERENCES [Month](ID),
	SubcategoryID INT NOT NULL FOREIGN KEY REFERENCES Subcategory(ID),
	BudgetedAmountCents INT NULL,
	ActualAmountCents INT NOT NULL
);