USE budgeter;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Category')
BEGIN
    CREATE TABLE Category
    (
        ID INT IDENTITY(1,1) CONSTRAINT PK_Category_ID PRIMARY KEY,
        [Name] VARCHAR(100) NOT NULL,
        BankAccountID INT NOT NULL FOREIGN KEY REFERENCES BankAccount(ID),
        IsCredit BIT NOT NULL DEFAULT(0)
    );
END;