USE budgeter;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Person')
BEGIN
    CREATE TABLE dbo.Person
    (
        ID INT PRIMARY KEY CLUSTERED,
        [Name] VARCHAR(100),
        Job_ID INT FOREIGN KEY REFERENCES Job(ID) 
    );
END;