USE budgeter;

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'MonthlyBudget')
BEGIN
    CREATE TABLE dbo.MonthlyBudget
    (
        ID INT PRIMARY KEY CLUSTERED,
        MonthID INT NOT NULL FOREIGN KEY REFERENCES [Month](ID),
        SubcategoryID INT NOT NULL FOREIGN KEY REFERENCES Subcategory(ID),
        Amount decimal(9,2) NOT NULL
    );
END;